PENALTY_DEFINITION

#This should actually enfore that there's BETWEEN 1 and 3 tyrosines in there, since I usually have to go back and add surface tyrosines anyway

# Define residue types to control
TYPE TYR

# Declare desired quantity of these residues
ABSOLUTE 2

# Set the penalty for having too few, at the desired number, and too many of the specified residues
PENALTIES 100 0 0 0 100

# Set how many residues you can be below the desired quantity before a penalty is applied. Since
# this value is a delta, the desired number of residues is "0", or zero residues away from the target.
# Therefore, "-1" indicates that the penalty will be applied once there is one fewer than the
# desired quantity
DELTA_START -2

# Set how many residues you can be above the desired quantity before a penalty is applied. Since
# this value is a delta, the desired number of residues is "0", or zero residues away from the target.
# Therefore, "1" indicates that the penalty will be applied once there is one more than the
# desired quantity
DELTA_END 2

#set how the penalties are applied
BEFORE_FUNCTION CONSTANT
AFTER_FUNCTION QUADRATIC
END_PENALTY_DEFINITION
