#!/usr/bin/env python

import os
import sys

import numpy as np
import pandas as pd


files = sys.argv[1:]


records = []

for file in files:
    if ( "features" in file ):
        continue
    dat = np.load(file)
    lddt = np.min(dat['lddt'])

    name = os.path.basename(file).replace(".npz", "")

    records.append({"description":name, "lddt":lddt})


df = pd.DataFrame(records)

df.to_csv("summary.txt", sep=" ", index=None)

